Repository GarudaHacks/web-be, pull requests merged in 2025-05, with the labels that each got.

#20 fix: controllers & middlewares
  functions/.eslintrc.js
  functions/src/controllers/application_controller.ts
  functions/src/controllers/auth_controller.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/middlewares/csrf_middleware.ts
  functions/src/middlewares/role_middleware.ts
Labels: Review effort 5/5

#21 Merge from dev
  .gitignore
  docs/application-endpoints.md
  functions/.eslintrc.js
  functions/package-lock.json
  functions/package.json
  functions/src/config/firebase.ts
  functions/src/controllers/application_controller.ts
  functions/src/controllers/auth_controller.ts
  functions/src/index.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/middlewares/csrf_middleware.ts
  functions/src/middlewares/role_middleware.ts
  functions/src/models/role.ts
  functions/src/routes/application.ts
  functions/src/routes/auth.ts
  functions/src/routes/index.ts
  functions/src/routes/ticket.ts
  functions/src/routes/user.ts
  functions/src/server.ts
  functions/src/types/application_types.ts
  functions/src/types/express.ts
  functions/src/utils/fake_data_populator.ts
  functions/src/utils/jwt.ts
Labels: Review effort 4/5

#22 fix: firebase admin version
  functions/.eslintrc.js
  functions/package-lock.json
  functions/package.json
  functions/src/config/firebase.ts
  functions/src/index.ts
  functions/src/routes/application.ts
  functions/src/server.ts
  functions/src/utils/fake_data_populator.ts
Labels: Review effort 2/5

#24 feat: redacted logging
  functions/src/server.ts
Labels: Review effort 2/5

#25 fix: csrf middleware
  functions/src/middlewares/csrf_middleware.ts
Labels: Review effort 2/5

#27 feat: reset password
  functions/.eslintrc.js
  functions/package-lock.json
  functions/package.json
  functions/src/controllers/auth_controller.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/middlewares/csrf_middleware.ts
  functions/src/routes/auth.ts
  functions/src/server.ts
Labels: Review effort 3/5

#34 Bugfix/form validations
  functions/src/config/firebase.ts
  functions/src/controllers/application_controller.ts
Labels: Review effort 3/5

#37 Merge from Dev
  functions/src/controllers/auth_controller.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/middlewares/csrf_middleware.ts
  functions/src/routes/auth.ts
Labels: Review effort 3/5

#39 Attach uid to applications
  functions/src/controllers/application_controller.ts
Labels: Review effort 2/5
