Repository GarudaHacks/web-be, pull requests merged in 2025-04, with the labels that each got.

#13 feat: logout
  functions/src/controllers/auth_controller.ts
  functions/src/routes/auth.ts
Labels: Review effort 2/5

#14 Auth
  functions/package-lock.json
  functions/package.json
  functions/src/config/firebase.ts
  functions/src/controllers/auth_controller.ts
  functions/src/controllers/users_controller.ts
  functions/src/index.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/routes/auth.ts
  functions/src/server.ts
  functions/src/utils/camel_case.ts
  functions/src/utils/fake_data_populator.ts
Labels: Review effort 4/5

#16 refactor: user
  functions/src/controllers/auth_controller.ts
  functions/src/controllers/user_controller.ts
  functions/src/controllers/users_controller.ts
  functions/src/models/user.ts
  functions/src/routes/index.ts
  functions/src/routes/user.ts
Labels: Review effort 3/5

#17 feat: ticket
  functions/src/controllers/ticket_controllers.ts
  functions/src/models/ticket.ts
  functions/src/routes/index.ts
  functions/src/routes/ticket.ts
Labels: Review effort 2/5

#18 Auth & Ticket
  functions/src/controllers/auth_controller.ts
  functions/src/controllers/ticket_controllers.ts
  functions/src/controllers/user_controller.ts
  functions/src/controllers/users_controller.ts
  functions/src/models/ticket.ts
  functions/src/models/user.ts
  functions/src/routes/index.ts
  functions/src/routes/ticket.ts
  functions/src/routes/user.ts
Labels: Review effort 3/5

#19 Feature/be 01 endpoints for user and application
  .gitignore
  docs/application-endpoints.md
  functions/package-lock.json
  functions/package.json
  functions/src/config/firebase.ts
  functions/src/controllers/application_controller.ts
  functions/src/controllers/auth_controller.ts
  functions/src/index.ts
  functions/src/middlewares/auth_middleware.ts
  functions/src/middlewares/csrf_middleware.ts
  functions/src/middlewares/role_middleware.ts
  functions/src/models/role.ts
  functions/src/routes/application.ts
  functions/src/routes/auth.ts
  functions/src/routes/index.ts
  functions/src/routes/ticket.ts
  functions/src/routes/user.ts
  functions/src/server.ts
  functions/src/types/application_types.ts
  functions/src/types/express.ts
  functions/src/utils/fake_data_populator.ts
  functions/src/utils/jwt.ts
Labels: Review effort 4/5
